name: Check the spelling in Markdown files
run-name: ${{ github.actor }} triggered a spellcheck on branch ${{ github.ref }}...
on: push
jobs:
  spellcheck-en-us:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v7
        with:
          files: '**/*.md'
          root: 'en-US'
          suggestions: true
