name: Validate Markdown files
run-name: Validation triggered on branch ${{ github.ref }}by ${{ github.actor }}...
on: push
jobs:
  lint-shared-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          config: '.markdownlint-cli2.yaml'
          globs: |
            README.md
  lint-en-us:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          config: '.markdownlint-cli2.yaml'
          globs: 'en-US/**/*.md'
  spellcheck-en-us:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v7
        with:
          files: '**/*.md'
          root: 'en-US'
          suggestions: true
