name: Validate Markdown files
run-name: Validation triggered on branch ${{ github.ref }} by ${{ github.actor }}...
on: push
jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          config: '.markdownlint-cli2.yaml'
          globs: |
            **/*.md
            !LICENSE.md
            !assets/fonts
  spellcheck-shared-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v7
        with:
          files: '*.md'
          root: '.'
          suggestions: true
          strict: true
  spellcheck-en-US:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v7
        with:
          files: './en-US/**/*.md'
          config: './en-US/cspell.config.yaml'
          suggestions: true
          strict: true
  spellcheck-es-MX:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Spanish cspell dictionary
        # CSpell doesn't have a Mexican Spanish dictionary according to https://github.com/streetsidesoftware/cspell-dicts,
        # so we're using the Spanish (Spain) dictionary as the best approximation.
        run: npm install --no-save @cspell/dict-es-es
      - run: echo "ls $(pwd):" && ls && echo "ls $(pwd)/es-MX:" && ls es-MX
      - uses: streetsidesoftware/cspell-action@v7
        with:
          files: './es-MX/**/*.md'
          config: './es-MX/cspell.config.yaml'
          suggestions: true
          strict: true
  spellcheck-de-DE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install German cspell dictionary
        run: npm install --no-save @cspell/dict-de-de
      - run: echo "ls $(pwd):" && ls && echo "ls $(pwd)/de-DE:" && ls de-DE
      - uses: streetsidesoftware/cspell-action@v7
        with:
          files: './de-DE/**/*.md'
          config: './de-DE/cspell.config.yaml'
          suggestions: true
          strict: true
