name: Validate Markdown files
run-name: Validation triggered on branch ${{ github.ref }} by ${{ github.actor }}...
on: push
jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          config: '.markdownlint-cli2.yaml'
          globs: |
            **/*.md
            !LICENSE.md
            !assets/fonts
  spellcheck-shared-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v7
        with:
          files: '*.md'
          root: '.'
          suggestions: true
          strict: true
  spellcheck-en-us:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v7
        with:
          files: 'en-US/**/*.md'
          root: '.'
          suggestions: true
          strict: true
  spellcheck-de-de:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install German cspell dictionary
        run: npm install --no-save @cspell/dict-de-de
      - uses: streetsidesoftware/cspell-action@v7
        with:
          files: '**/*.md'
          root: './de-DE'
          config: 'de-DE/cspell.config.yaml'
          suggestions: true
          strict: true
